routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

Route::resource('transactions','TransactionsController')->except([
    'show','destroy'
])->middleware('auth');

Route::get('/transactions/delete/{id}','TransactionsController@destroy')->middleware('auth');
//Route::get('/transactions/update/{id}','TransactionsController@update');

app/Transactions.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transactions extends Model
{
    protected $fillable = [
        'tx_amount','division','status'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use App\Transactions;
use Illuminate\Http\Request;

class TransactionsController extends Controller
{

    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax())
        {
            return datatables()->of(Transactions::latest()->get())
                    ->addColumn('action', function($data){
                        if($data->status == 'Pending')
                        {
                            $button = '<a class="btn btn-primary btn-sm" href="/transactions/'.$data->id.'/edit" name="edit"><i class="fas fa-edit"></i></a>';
                            $button .= '&nbsp;&nbsp;';
                            $button .= '<a class="btn btn-danger btn-sm" href="/transactions/delete/'.$data->id.'" name="delete"><i class="fas fa-trash"></i></a>';
                        }
                        else
                            $button = '<a class="btn btn-danger btn-sm" href="/transactions/delete/'.$data->id.'" name="delete"><i class="fas fa-trash"></i></a>';
                        return $button;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        return view('transactions.read');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('transactions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'tx_amount'=>'required|numeric'
        ]); 

        $transaction = new Transactions;
        $tx_amount = $request->input('tx_amount');
        if ($tx_amount <= 1000000)
        {
            $transaction->division = 'Finance';
            $transaction->status = 'Approved';
        }
        elseif ($tx_amount > 1000000 && $tx_amount <= 5000000)
        {
            $transaction->division = 'Direktur Keuangan';
            $transaction->status = 'Pending';
        }
        else
        {
            $transaction->division = 'Direktur Utama';
            $transaction->status = 'Pending';
        }
        $transaction->tx_amount = $request->input('tx_amount');    
        
        $transaction->save();

        return redirect('/transactions')->with('success','New transaction has been successfully inputted');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transactions  $transactions
     * @return \Illuminate\Http\Response
     */
    public function show(Transactions $transactions)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transactions  $transactions
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $transaction = Transactions::find($id);
        return view('transactions.update', ['transaction' => $transaction]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transactions  $transactions
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $this->validate($request,[
            'tx_amount'=>'required|numeric',
            'status'=>'required'
        ]);

        $status = $request->input('status');
        $tx_amount = $request->input('tx_amount');

        $transaction = Transactions::find($id);
        $transaction->tx_amount = $tx_amount;    
        $transaction->status = $status;
        $transaction->save();

        return redirect('/transactions')->with('success','Transaction has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transactions  $transactions
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transaction = Transactions::find($id);
        $transaction->delete();

        return redirect('/transactions')->with('alert','Deleted Transaction');
    }
}

resources/views/home.blade.php
@extends('adminlte::page')

@section('title', 'LATIHAN1')

@section('content_header')
    <h1>
        Dashboard
        <small>Latihan1</small>
    </h1>
    
    <ol class="breadcrumb">
        <li class="active"><a href="#"><i class="fa fa-home"></i> Dashboard</a></li>
    </ol>
@stop

@section('content')
<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">CPU Traffic</span>
          <span class="info-box-number">90<small>%</small></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-red"><i class="fa fa-google-plus"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Likes</span>
          <span class="info-box-number">41,410</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>

    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-green"><i class="ion ion-ios-cart-outline"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Sales</span>
          <span class="info-box-number">760</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">New Members</span>
          <span class="info-box-number">2,000</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
@stop

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/transactions/create.blade.php
@extends('adminlte::page')

@section('title', 'LATIHAN1')

@section('content_header')
    <h1>
        Transactions Request
        <small>Latihan1</small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-home"></i> Dashboard</a></li>
        <li><a href="/transactions">Transactions</a></li>
        <li class="active">New Request</li>
    </ol>
@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Input New Request</h3>
        </div>
        <div class="box-body">
            <form action="{{ route('transactions.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label>Transaction Amount (Rp.)</label>
                <input type="number" name="tx_amount" class="form-control" placeholder="Rp. 123456" value="{{ old('tx_amount') }}">

                    @if($errors->has('tx_amount'))
                        <div class="text-danger">
                            {{ $errors->first('tx_amount')}}
                        </div>
                    @endif

                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Input">
                </div>
            </form>
        </div>
    </div>
@stop

resources/views/transactions/read.blade.php
@extends('adminlte::page')

@section('title', 'LATIHAN1')

@section('content_header')
    <h1>
        Transactions
        <small>Latihan1</small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-home"></i> Dashboard</a></li>
        <li class="active">Transactions</li>
    </ol>
@stop

@section('content')
    @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
    @endif
    @if(session()->has('alert'))
        <div class="alert alert-danger">
            {{ session()->get('alert') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
    @endif
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Transactions Request</h3>
        </div>
        <div class="box-body">
            <a href="/transactions/create" class="btn btn-primary">Input New Request</a>
            <br>
            <br>
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped" id="transact_table" >
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Amount (Rp.)</th>
                            <th>Time</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@stop

@section('adminlte_js')
    <script>
        $(document).ready(function(){
            $('#transact_table').DataTable({
            searching: false,
            processing: true,
            serverSide: true,
            aaSorting: [[2,'desc']],
            ajax:{
            url: "{{ route('transactions.index') }}",
            },
            columns:[
            // {
            //     data: 'image',
            //     name: 'image',
            //     render: function(data, type, full, meta){
            //     return "<img src={{ URL::to('/') }}/images/" + data + " width='70' class='img-thumbnail' />";
            //     },
            //     orderable: false
            // },
            {
                data: 'id',
                render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                },
                orderable: false
            },
            {
                data: 'tx_amount',
                name: 'tx_amount',
                render: function(data,type,row){
                    return 'Rp. ' + row['tx_amount'];
                },
                orderable: false
            },
            {
                data: 'created_at',
                name: 'created_at',
                orderable: false
            },
            {
                data: 'status',
                name: 'status',
                render: function(data,type,row){
                    var r = '';
                    if(row['tx_amount'] > 1000000 && row['tx_amount'] <= 5000000 && row['status'] == 'Pending')
                        r = 'Pending (Need Direktur Keuangan Approval)';
                    else if(row['tx_amount'] > 5000000 && row['status'] == 'Pending')
                        r = 'Pending (Need Direktur Utama Approval)';
                    else if (row['status']=='Declined')
                        r = 'Declined';
                    else if (row['status'] == 'Approved')
                        r = 'Approved';
                    else
                        r = 'Pending Approval';
                    return r;
                },
                orderable: false
            },
            {
                data: 'action',
                name: 'action',
                orderable: false
            }
            ]
            });
        });
    </script>
@stop

resources/views/transactions/update.blade.php
@extends('adminlte::page')

@section('title', 'LATIHAN1')

@section('content_header')
    <h1>
        Transactions Request
        <small>Latihan1</small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-home"></i> Dashboard</a></li>
        <li><a href="/transactions">Transactions</a></li>
        <li class="active">Edit Request</li>
    </ol>
@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Edit Request</h3>
        </div>
        <div class="box-body">
        <form action="/transactions/{{$transaction->id}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label>Transaction Amount (Rp.)</label>
                <input type="number" name="tx_amount" class="form-control" placeholder="Rp. 123456" value="{{ $transaction->tx_amount }}">

                    @if($errors->has('tx_amount'))
                        <div class="text-danger">
                            {{ $errors->first('tx_amount')}}
                        </div>
                    @endif
                <br>
                <div class="form-group">
                    <label>Set Status</label>
                    <br>
                    <select class="custom-select" name="status">
                        <option value="Approved" selected>Approve</option>
                        <option value="Declined">Decline</option>
                      </select>
                      @if($errors->has('status'))
                      <div class="text-danger">
                          {{ $errors->first('status')}}
                      </div>
                  @endif  
                </div>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Update">
                </div>
            </form>
        </div>
    </div>
@stop